### PR TITLE
Offline First Experience with Caching and Sync Status Indicator

### PR DESCRIPTION
**Pull request by tarunkumar2005**
WHen you are offline it will show this page :- 

image

I have properly and professionally done it. 

@anuj123upadhyay Please check this PR and merge this and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and please put it a level 3 as it is very important part of the website and also it is typical to implement. Thank you.

### CODE REVIEW

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
hey @tarunkumar2005  there is some error in production can just go through and try to resolve the error

**Comment by tarunkumar2005** [comment]
@anuj123upadhyay Will check and get back to you.

**Comment by tarunkumar2005** [comment]
@anuj123upadhyay Can you share a screenshot or so as i can't see the build logs on vercel and when i am building it using npm run build locally it is working fine ??

**Comment by tarunkumar2005** [comment]
@anuj123upadhyay Now can you check there were conflicting dependencies.

**Comment by anuj123upadhyay** [comment]
Still there is issue

**Comment by tarunkumar2005** [comment]
@anuj123upadhyay I have downgraded the version of styled-components to 4.0.0 as you simple chatbot package works on that only so you need to fix this issue i didn't changed any of these two, i don't know how it was not before when you merged previous PRs.

**Pull request merged**
