### PR TITLE
 Added Features Page with Responsive Layout and Animations

### LINKED ISSUE #119: Adding Features Page
Adding a pages that shows features that we offer gives more readability and enhances user experience.

And linking it to the footer.

image

@anuj123upadhyay please assign this to me.

### PR DESCRIPTION
**Pull request by govindumeesala**
closes #119 

## Description:
Implemented a Features page showcasing the main features of our blogging platform.
### Each feature includes:
- Align with the existing website and style and also added the darkmode to the page.
- An icon for visual appeal.
- A title and description for clarity on what the platform offers.
- Features are presented in a responsive grid layout that adapts across devices (mobile, tablet, desktop).
- Added smooth Framer Motion animations for card fade-in effects and scaling on hover, enhancing user engagement.
- Utilized Tailwind CSS for styling, providing a clean, modern, and mobile-friendly interface.
- This addition enhances the UI/UX of the website by clearly presenting the platform's key features in an interactive and visually appealing manner.

image

@anuj123upadhyay  please check once

### CODE REVIEW

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by govindumeesala** [comment]
Heyy @anuj123upadhyay  It will be encouragement for me. If you merge this.
It would be agreat help.

**Comment by govindumeesala** [comment]
@anuj123upadhyay  Heyyy please consider checking this out.

**Comment by govindumeesala** [comment]
@anuj123upadhyay Helloo. I have raise this pr last week, you approved but didnt merge.
Please consider checking it. It will be a lot help to me. Kindly consider checking this once. 

It will help me to be in top 50 contributors.

**Comment by anuj123upadhyay** [comment]
Bro there is a reason behind not merging this pr this pr causes issue in deployment

**Comment by anuj123upadhyay** [comment]
And until deployment is not successful, the branch couldnot  be able to merger

**Comment by govindumeesala** [comment]
> And until deployment is not successful, the branch couldnot be able to merger

Should I raise a new PR

**Comment by anuj123upadhyay** [comment]
As your wish

**Pull request closed without merging**
