### PR TITLE
changed Favicon

### PR DESCRIPTION
**Pull request by AyushSharma72**
i changed the favicon 

image

### CODE REVIEW

**Comment by AyushSharma72** [comment]
changed 

image

**Comment by anuj123upadhyay** [comment]
Okk I will merge your pr

**Comment by AyushSharma72** [comment]
> Okk I will merge your pr

dont forget to add gssoc-ext and level2 labels

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by Hemu21** [comment]
@anuj123upadhyay  I am one of the program managers of gssoc-ext. can you please change the level. It is the favicon update. So  level 1 is needed not level 2. I hope you understand. Can you please update the label

**Pull request merged**
