### PR TITLE
Category Page made @8

### PR DESCRIPTION
**Pull request by inkerton**
image

image

Issue #428

### CODE REVIEW

**Comment by inkerton** [comment]
Hey @anuj123upadhyay It's 5 in the morning. I have only 3 tasks as per me left Search, Edit post and Abit of styling to this Page
image

I will do these by 3o'clock today. Then I guess everything is functional and finished If any Pr has any conflicts then let me know and If you need any changes then also do let me know I would try to do all those possible within the time limit today.

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
hey @inkerton  now after merging the prs the project have some routing problems can you please solve this

**Comment by anuj123upadhyay** [comment]
make a new prs for that

**Comment by anuj123upadhyay** [comment]
please try to solve the project becomes totally non-functional

**Comment by anuj123upadhyay** [comment]
go the main deployment link from this repo and analyse the problem

**Comment by anuj123upadhyay** [comment]
hey @inkerton  
Screenshot 2024-11-10 at 11 37 46 AM
i am unable to login into my account what is the problem it happened due to some conflict,
please try to resolve those error , as well as above error

**Comment by inkerton** [comment]
> hey @inkerton Screenshot 2024-11-10 at 11 37 46 AM i am unable to login into my account what is the problem it happened due to some conflict, please try to resolve those error , as well as above error

Ok I will check  Them out .

**Comment by inkerton** [comment]
> hey @inkerton Screenshot 2024-11-10 at 11 37 46 AM i am unable to login into my account what is the problem it happened due to some conflict, please try to resolve those error , as well as above error

I could not find any createemailsession . Thought their is a createEmailPasswordSession

It is working fine for me. Try to merge my new Prs and let me know if you are still getting this error the routing issue too. I made a pr for that try that first if that solves the error if not then I have an idea i will try something else.

**Comment by anuj123upadhyay** [comment]
No , now it's working fine as I changed it

**Comment by inkerton** [comment]
Ohkay, That's good the only edit post and skeleton addition is left #437 and #439 . Merge these then

**Pull request merged**
