### PR TITLE
Implemented Responsiveness and PropTypes to Core Pages and Components

### PR DESCRIPTION
**Pull request by manu-hn**
This PR implements responsiveness for the homepage, navbar, footer, login, and signup pages. Additionally, PropTypes have been added to key components to enhance type safety. These improvements ensure a better user experience and maintain code reliability.

### CODE REVIEW

**Review by anuj123upadhyay — COMMENTED** [review]
can you just give me the screenshot of the new output

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by manu-hn** [comment]
> can you just give me the screenshot of the new output

Hi,

I’ve recorded my screen to showcase the updates. I’ve only worked on the responsiveness, not the backend with Appwrite, but you can see that the functionalities are working properly.

Let me know if you have any questions
https://www.loom.com/share/ac6ad978367a4b4494fccda995c45a38?sid=725b4cee-28f7-40b8-bb76-e33ade135f73

**Comment by manu-hn** [comment]
Hey @anuj123upadhyay , thank you for your patience. It seems the issue is a CORS error. Please install the free Allow CORS browser extension and try again.

**Comment by anuj123upadhyay** [comment]
i am closing this pr as this has already been done by another pr

**Pull request closed without merging**
