### PR TITLE
hero section

### PR DESCRIPTION
**Pull request by inkerton**
Changed componenets to Components
Added components folder for shadcn
Added Hero section

### CODE REVIEW

**Comment by inkerton** [comment]
this is in response to the issue #20

**Comment by inkerton** [comment]
@anuj123upadhyay  Check out this PR I listed the changes above

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
This branch has conflicts that must be resolved

**Comment by inkerton** [comment]
I dont have write access to see or resolve conflicts can you send me the ss .

**Comment by inkerton** [comment]
image

**Comment by inkerton** [comment]
I got the issue i changed the componenets folder name to Components. The name is the conflict I would say change the name in your repo to match mine and also correct the spelling error @anuj123upadhyay  then everybody else will be able to fetch the changes.

**Comment by inkerton** [comment]
@anuj123upadhyay  I changed the folder name back to **componenets**.
Now It has No conflicts. I also added the Pricing page here also have a look 
image

Merge the PR first then I will add the pricing page again in a seperate PR Currently I am deleting it.

**Comment by inkerton** [comment]
@anuj123upadhyay merge the PR Now with no conflicts then I will add the pricing page again I have been working on that since last 2 days so If you want any changes in the pricing page tell me I will do it .

**Comment by anuj123upadhyay** [comment]
Could not resolve "./pages/Pricing.jsx" from "src/main.jsx"  uring epoyment just remove this error , i will merge this pr

**Comment by anuj123upadhyay** [comment]
then raise another pr for pages , also please include the free tier program  also

**Comment by inkerton** [comment]
@anuj123upadhyay Removed the error .

Now check and tell me

**Comment by inkerton** [comment]
Should I add another box or should I just change the Starter Pack to 0$ and all things accessible. I will add a 'coming soon ' sign to the Pro Pack @anuj123upadhyay

**Comment by anuj123upadhyay** [comment]
After 1 pm I will able to merge your all PRs

**Comment by anuj123upadhyay** [comment]
Yes , you can do that make pro pack and which having this status of comming soon 
> Should I add another box or should I just change the Starter Pack to 0$ and all things accessible. I will add a 'coming soon ' sign to the Pro Pack @anuj123upadhyay

**Comment by inkerton** [comment]
@anuj123upadhyay  Merge this PR first then you will be able to merge the Pricing Page and then Affiliate Programs page.

**Pull request merged**
