### PR TITLE
Customer support Page changed

### PR DESCRIPTION
**Pull request by inkerton**
**BEFORE**

image

<hr/>
**AFTER**

image

### CODE REVIEW

**Comment by inkerton** [comment]
@anuj123upadhyay 

This is in response to the issue #97

**Comment by inkerton** [comment]
@anuj123upadhyay 

I haven't added motions in this Page first you confirm to me if I should add that then I will add those here.

This is general layout of the page that I canged Button on hover to black ,etc. You can merge this easily.

image

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by Hemu21** [comment]
@MastanSayyad

**Comment by inkerton** [comment]
I not only animated headings, paragraphs, and cards but also made the entire UI design, making the page more visually appealing and interactive.

After receiving confirmation from my mentor, I proceeded with the animation implementation. These subtle yet impactful animations guide users seamlessly through the page, enhancing engagement and overall satisfaction. I prioritized performance and accessibility, ensuring the animations are smooth and don't hinder user experience, especially for users with disabilities.

By combining thoughtful UI design and strategic animation, I believe I've delivered a substantial improvement to the project, making it more user-friendly and visually compelling.

**Review by MastanSayyad — COMMENTED** [review]
Hi @inkerton I think you have mistakenely added your comment here, in this PR there are No such changes you mentioned 

These are the actual changes pf your work, you have centered the button horizontally and vertically within its container.  Padding, font size, text color, and a shadow are applied. but he The button could be more accessible

image

Here The card is centered and aligned in a column.
`transition-transform transform hover:scale-105` makes the card scale up slightly on hover.

image

@inkerton @anuj123upadhyay kindly reduced labels to `level 2`







image

**Pull request merged**
