### PR TITLE
Categorical display of Posts : 3

### PR DESCRIPTION
**Pull request by inkerton**
image

### CODE REVIEW

**Comment by inkerton** [comment]
@anuj123upadhyay I resolved the conflicts Now you can merge.

**Comment by inkerton** [comment]
@anuj123upadhyay Please merge 
#175 
#173 
#147 
#111 

Then I will work on displaying the blogs category-wise on all posts I will show only 3-4 blogs and then the user can visit that category to view all blogs under that category.

**Comment by anuj123upadhyay** [comment]
Hey @inkerton  all of these pr are creating deployment failed , try to resolve the errors and after that make another pr for that

**Comment by inkerton** [comment]
I resolved them yesterday night. Try mering them and let me know if any conflicts is still arising
@anuj123upadhyay

**Comment by inkerton** [comment]
This PR is in response to the issue #174 

@anuj123upadhyay Let me know when You are free .

**Comment by anuj123upadhyay** [comment]
I am currently in college my college timing is 8 to 4 pm

**Comment by inkerton** [comment]
@anuj123upadhyay Ohkay anuj 

[https://nexmeet-lake.vercel.app/](https://nexmeet-lake.vercel.app/)
Visit this their is an animation of ralling drops added in here I want to add this what do you think ?

And please merge all the PRs then I want to delete all branches and work via new branches I have 12 branches in this repo. If any error or conflict occurs let me know i will solve it right then.

**Comment by inkerton** [comment]
@anuj123upadhyay You got back home ?

**Comment by inkerton** [comment]
@anuj123upadhyay Hey anuj! 
Please merge these if they are still not merging i will close these and create new PRs. Until You merge the categories PR i made I won't be able to work further. Showing blogs of a particular category or add comment section below the blog page.
#175 
#173 
#147 
#111 


Let me know ohkay Thanks!

**Comment by anuj123upadhyay** [comment]
Hey @inkerton  I will merge your PRs after 4-5 pm as I am suffering from fever right now, as I feel better I will merge your prs

**Comment by inkerton** [comment]
No issues buddy get well soon @anuj123upadhyay

**Comment by anuj123upadhyay** [comment]
hey @inkerton can you please also change the default favicon that is coming on every post. make it as it is as the image selected by the writer

**Comment by inkerton** [comment]
@anuj123upadhyay Resolved conflicts .

Try merging now please

**Comment by inkerton** [comment]
> hey @inkerton can you please also change the default favicon that is coming on every post. make it as it is as the image selected by the writer

Yeah I saw it too @anuj123upadhyay Will work on it too today Merge this PR also please This is my last PR left then I will start making new ones .

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by inkerton** [comment]
@anuj123upadhyay Resolved Conflicts

**Pull request merged**
