### PR TITLE
Adding category to database: 2

### PR DESCRIPTION
**Pull request by inkerton**
This is a new PR please merge it and after #203 No conflicts will arise then 

then merge the PRs in numbering 
#175 
#204 
#205 
#207 
#209

### CODE REVIEW

**Comment by inkerton** [comment]
Conflicts Resolved
@anuj123upadhyay

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by Hemu21** [comment]
@MastanSayyad

**Review by MastanSayyad — COMMENTED** [review]
kindly dont give labels like level 3 for dependencies please remove the labels from this PR I can see other PRs have labels but this should not have any, it is devs resposibility to take care of this while making changes @anuj123upadhyay

**Comment by inkerton** [comment]
this was a pr made in sequence to another PR. that one was accepted first so the file changes reduced. here in the pr I originally made had changes in appwrite db functions to save the category as the tiltle of the PR.

**Comment by MastanSayyad** [comment]
@inkerton I see those PRs listed above already has level 3s given, level3 again to these dependencies is not fair It is basic responsibilty of the dev itself, and, therefore this would have no labels of levels @Hemu21 correct me if I'm wrong

and @anuj123upadhyay add me as a collaborator in your repo as we're reviewing contributors we have to revisit the repo and reduce levels for some contributors

**Pull request merged**
