### PR TITLE
Update AllPost.jsx

### PR DESCRIPTION
**Pull request by inkerton**
> hey @inkerton try to resolve this issue also Screenshot 2024-11-10 at 2 22 08 PM

Added skeleton like this 
image

So it should be resolved now @anuj123upadhyay

### CODE REVIEW

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
hey @inkerton 
Screenshot 2024-11-10 at 5 19 18 PM
and 
is in your app
Screenshot 2024-11-10 at 5 23 11 PM
this small blck box of vercel comes or not

**Comment by anuj123upadhyay** [comment]
the error is still there

**Comment by anuj123upadhyay** [comment]
@inkerton  please try to respond as early as possible  , what could you think this is a errror somewhere there is a map in the allPost page that causes issue

**Comment by anuj123upadhyay** [comment]
are you working on it

**Comment by inkerton** [comment]
Yes let me see.

**Comment by anuj123upadhyay** [comment]
hey @inkerton   are you working on it

**Pull request merged**
