### PR TITLE
Website Theme Changing on Mode Switch

### PR DESCRIPTION
**Pull request by AnushkaChouhan25**
Fix Issue - #373 

The website theme is now updating correctly when switching between light and dark modes. When the mode is tripped, the website applies the new theme, and consistent styling across the site.

image
image
image

### CODE REVIEW

**Comment by anuj123upadhyay** [comment]
You dark. Color is too dark  please make it some fade only some fade

**Comment by anuj123upadhyay** [comment]
please try to make it such a way that some outline can also be visible through it to make it good looking it is like a total dark page

**Comment by anuj123upadhyay** [comment]
there should be a different - different dark shade for nav bar , for main section and for footer ,

**Comment by AnushkaChouhan25** [comment]
@anuj123upadhyay ok I understood

**Comment by AnushkaChouhan25** [comment]
@anuj123upadhyay is this dark theme is ok, it is aligning with website theme also 
image

**Comment by AnushkaChouhan25** [comment]
or this one ?
image

**Comment by anuj123upadhyay** [comment]
the second one

**Comment by AnushkaChouhan25** [comment]
@anuj123upadhyay DONE

**Review by anuj123upadhyay — APPROVED** [review]

**Pull request merged**
