### PR TITLE
Privacy Page UI Enhanced

### PR DESCRIPTION
**Pull request by inkerton**
This is in response to the issue #92 

This PR has all headings black.

https://github.com/user-attachments/assets/6efe551d-be35-4efb-8708-0e4f19a5c92c

### CODE REVIEW

**Review by anuj123upadhyay — COMMENTED** [review]
try to make all the heading in accordance with the whole project

**Review by anuj123upadhyay — APPROVED** [review]
okk it looks fine by the way

**Comment by inkerton** [comment]
I not only animated headings, paragraphs, and cards but also made the entire UI design, making the page more visually appealing and interactive.

After receiving confirmation from my mentor, I proceeded with the animation implementation. These subtle yet impactful animations guide users seamlessly through the page, enhancing engagement and overall satisfaction. I prioritized performance and accessibility, ensuring the animations are smooth and don't hinder user experience, especially for users with disabilities.

By combining thoughtful UI design and strategic animation, I believe I've delivered a substantial improvement to the project, making it more user-friendly and visually compelling.

**Review by MastanSayyad — COMMENTED** [review]
The `<motion.div>` tag is a component from the `Framer Motion` library, which allows for easy animations and transitions in React applications. By using `<motion.div>` instead of a regular `<div>`, developers can add animations or transitions with minimal code.

image
image
image
image

After reviewing most of your PRs, I noticed that you've primarily used `<motion.div>` to wrap elements without implementing complex animations or configurations. This represents a minor UI enhancement rather than a significant functional change, especially if the component is simply wrapped for a subtle effect without much customization.

@anuj123upadhyay, based on this, please adjust the label from `level 3` to `level 2`.

@inkerton, please don't feel discouraged. I am reviewing everyone throughout the leaderboard, and points are being adjusted based on each PR's contributions. Some PRs require review for point adjustments where necessary. @Hemu21 is our tech lead and a program manager, so if they requested a review from me, it indicates that the code needed evaluation.

I appreciate your cooperation, and I encourage you to keep contributing to multiple repositories with unique contributions.

**Pull request merged**
