### PR TITLE
Delayed by 2 seconds

### PR DESCRIPTION
**Pull request by inkerton**

### CODE REVIEW

**Comment by inkerton** [comment]
@anuj123upadhyay Try this now I delayed the rendering by 2 seconds used the skeleton and also added length check before map .

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
: /vercel/path0/src/pages/AllPost.jsx:163:4
Expected ";" but found ":"
161|        </Container>
162|      </div>
163|    ) : (
   |      ^
164|      <>
165|        <div class="animate-pulse block-item shadow-md max-w-xl mx-auto mt-20">
 there is a error in deployment , check it out

**Comment by inkerton** [comment]
@anuj123upadhyay Done

**Comment by anuj123upadhyay** [comment]
It's working fine on localhost

**Comment by inkerton** [comment]
> It's working fine on localhost

yeah the skeleton was duplicated by mistake. May be that is why it showed the error

**Comment by anuj123upadhyay** [comment]
hey @inkerton   
now this error comes 
take your time and resolve it 
Screenshot 2024-11-10 at 6 50 41 PM

**Comment by anuj123upadhyay** [comment]
try componenets

**Comment by anuj123upadhyay** [comment]
hey @inkerton  please figure it out

**Comment by inkerton** [comment]
check now

**Pull request merged**
