### PR TITLE
draft posts fetched

### PR DESCRIPTION
**Pull request by inkerton**
This is in response to the issue #268 

https://github.com/user-attachments/assets/90d5837f-1a7a-464e-9b84-f5a0a663eb1c

### CODE REVIEW

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
hey @inkerton  can you just explain me that  weather i need to maintain  getCurrentUsersPosts(userId)  function or only  getCurrentUsersDraftPosts(userId)function or both

**Comment by anuj123upadhyay** [comment]
reply as soon as possible

**Comment by inkerton** [comment]
Both 
getCurrentUsersPosts- it fetches all posts written and published by the user
getCurrentUsersDraftPosts- it fetches all posts the user has labeled as inactive and draft.

I will work on edit next so they will be able to edit the draft posts and then post them .

**Comment by inkerton** [comment]
@anuj123upadhyay Resolved conflicts too

**Pull request merged**
