### PR TITLE
delete post fixed

### PR DESCRIPTION
**Pull request by inkerton**
this is in response to the issue #270 

https://github.com/user-attachments/assets/efc1681a-8c65-4d91-a7cb-36b60f4c7bad

### CODE REVIEW

**Comment by inkerton** [comment]
Hey! @anuj123upadhyay When will you be free or coming online I will merge any conflicts on the spot just let me know ok!

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by Hemu21** [comment]
@MastanSayyad can you check this

**Review by MastanSayyad — COMMENTED** [review]
Reduce the label to `level 2` @anuj123upadhyay and please add me as a collaborator we are reviewing contributors so we need access to reduce the score, thank you

**Comment by MastanSayyad** [comment]
@anuj123upadhyay if you are active then kindly respond to each PR I mentioned and do the needful, also add me as a collaborator asap

**Pull request merged**
