### PR TITLE
Displayed metadata , tags on all posts page and added styling to differentiate and display categories

### PR DESCRIPTION
**Pull request by inkerton**
image

image

This is in response to issue #343

### CODE REVIEW

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
Conflicting files
src/componenets/PostCard.jsx
src/pages/AllPost.jsx

**Comment by anuj123upadhyay** [comment]
try to make new pr

**Comment by inkerton** [comment]
@anuj123upadhyay Hey Happy diwali to you too 😊.
Since gssoc is now till 10th Nov i would love to contribute more after diwali.

**Comment by anuj123upadhyay** [comment]
Nice to hear

**Comment by anuj123upadhyay** [comment]
Installing dependencies...
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: medium-draft@0.5.18
npm error Found: react@18.3.1
npm error node_modules/react
npm error   react@"^18.2.0" from the root project
npm error   peer react@">=16.8.0" from @floating-ui/react-dom@2.1.2
npm error   node_modules/@floating-ui/react-dom

**Comment by inkerton** [comment]
@anuj123upadhyay Issue resolved

**Comment by anuj123upadhyay** [comment]
Of you have any prs remaining make those prs as soon as possible

**Comment by anuj123upadhyay** [comment]
still has some issues

**Comment by inkerton** [comment]
@anuj123upadhyay I am closing this one I made new PRs

**Pull request closed without merging**
