### PR TITLE
Added frontend and backend for feedback details

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue : #390 

Screenshot 2024-11-07 004012
Screenshot 2024-11-07 004023

This is the feedback form ui 
clean and clear ui 

Screenshot 2024-11-07 004047
On submitting the form this data get saved on database
in a efficient manner !!

### CODE REVIEW

**Comment by Sawan-Kushwah** [comment]
@anuj123upadhyay will i get level 3 for this PR ?

**Comment by Sawan-Kushwah** [comment]
@anuj123upadhyay please merge my both PR so that i can contribute more to "Megablog" ☺️
Else its create conflict

**Comment by anuj123upadhyay** [comment]
I will merge them btw 11 to 12 am today as I will free in this duration

**Comment by anuj123upadhyay** [comment]
I am messaging you through the mobile application of GitHub

**Comment by Sawan-Kushwah** [comment]
@anuj123upadhyay okay no worries

**Review by anuj123upadhyay — APPROVED** [review]

**Pull request merged**
