### PR TITLE
Toggle text color

### PR DESCRIPTION
**Pull request by Lakshay1838**
Fixes - #19
Implemented toggle dark mode design

### CODE REVIEW

**Review by anuj123upadhyay — APPROVED** [review]

**Comment by anuj123upadhyay** [comment]
instead of simple toggle the text color of the pages you can implement the functionality of dark mode and light mode in the same button as DarkMode and LightMode

**Comment by anuj123upadhyay** [comment]
just toggling the textcolor will be of no use

**Comment by Lakshay1838** [comment]
normal :
Screenshot 2024-10-07 165534
hover:
Screenshot 2024-10-07 165542
DarkMode
Screenshot 2024-10-07 165547

@anuj123upadhyay can you please check if ok then pls merge
Thanks

**Comment by Lakshay1838** [comment]
Dark Mode Button in light mode:
Screenshot 2024-10-07 233110
LightMode Button in dark mode:
Screenshot 2024-10-07 233120
@anuj123upadhyay i have added a feature see above 

could you pls merge it now

**Pull request closed without merging**
