### PR TITLE
changed components of Add Post: 6

### PR DESCRIPTION
**Pull request by inkerton**
This is in response to the issue #206

### CODE REVIEW

**Review by anuj123upadhyay — COMMENTED** [review]
can you please show me the output video of this

**Comment by inkerton** [comment]
Checkout the issue I added images in the issue itself @anuj123upadhyay

**Comment by inkerton** [comment]
After you accept the categories PR i will add metadata , and tags like this .

image

**Comment by inkerton** [comment]
https://github.com/user-attachments/assets/85406abc-163b-400f-b4bd-f45f837551a0

@anuj123upadhyay Category will also be shown here After you merge that PR.

**Review by anuj123upadhyay — APPROVED** [review]

**Pull request merged**
