### PR TITLE
added shacn and improved home page

### PR DESCRIPTION
**Pull request by inkerton**
this is the After and before images

**Before**
image

**After**
image

This is in response to the issues:
#4
#9 
#3  
#8

### CODE REVIEW

**Comment by inkerton** [comment]
Kindly add appropriate Level tag also so it would be easier for me to get my points. @anuj123upadhyay

**Comment by anuj123upadhyay** [comment]
Which level tag you want me to add name it , I will add it

**Comment by inkerton** [comment]
Since it took a whole day and I had to go through the whole repository kindly add a **level3** tag. I will now start working on the hero section of the home page if that's okay.

**Comment by inkerton** [comment]
Add a tag to my PR also either a level3 or level2 accordingly I haven't gotten any points for this PR also. @anuj123upadhyay

**Pull request merged**
